name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout o código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Rodar build do Next.js
      run: npm run build

    # - name: Rodar testes
    #   run: npm test
    #   # Se você ainda não tem testes, este passo pode dar erro ou ser removido.